apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: phoonum-sl-dev
  name: spring-config-deployment
  labels:
    app: spring-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config
  template:
    metadata:
      labels: 
        app: spring-config
        deployment: spring-config
    spec:
      containers:
      - name: spring-config
        image: phoonumsl/spring-config:latest
        ports:
          - containerPort: 8080
            protocol: TCP
strategy:
  type: Rolling
  rollingParams:
    timeoutSeconds: 600
    updatePeriodSeconds: 1
    intervalSeconds: 1
    maxSurge: 25%
    maxUnavailable: 25%
  triggers:
    - type: ConfigChange
paused: false