apiVersion: v1
kind: Service
metadata:
  name: spring-config-service
  namespace: phoonum-sl-dev
spec:
  selector:
    app: spring-config
    deployment: spring-config
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
